# Local Development Profile - PostgreSQL Database
spring:
  # JPA Configuration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # Atualiza o schema conforme necessário
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  # SQL Initialization
  sql:
    init:
      mode: always

  # H2 In-Memory Database Configuration for Local Development
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000
  
  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console

# JWT Configuration
jwt:
  public:
    key: "classpath:app.pub"
  private:
    key: "classpath:app.key"

# Logging
logging:
  level:
    org.springframework.security: DEBUG
    com.victorxavier: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG

# Server Configuration
server:
  port: 8080