# Spring Boot Application Configuration - Mock Profile
spring:
  # Active Profile Configuration
  profiles:
    active: default # Perfil padrão para mock/testes

  # JPA Configuration for Mock
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop # Cria e apaga o schema a cada execução
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  # SQL Initialization
  sql:
    init:
      mode: always

  # H2 In-Memory Database Configuration (Mock)
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;TIME ZONE=UTC
    username: sa
    password: "" # Senha vazia
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis123}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# JWT Configuration (comum para todos os perfis)
jwt:
  public:
    key: "classpath:app.pub"
  private:
    key: "classpath:app.key"

# Management and Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Logging Configuration
logging:
  level:
    org.springframework.security: WARN
    com.victorxavier: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

# Server Configuration
server:
  port: 8080

# Melhor Envio API Configuration
melhor-envio:
  api:
    base-url: ${MELHOR_ENVIO_BASE_URL:https://sandbox.melhorenvio.com.br/api/v2/me}
    token: ${MELHOR_ENVIO_TOKEN:your-sandbox-token-here}
    timeout: ${MELHOR_ENVIO_TIMEOUT:30000}
    sandbox: ${MELHOR_ENVIO_SANDBOX:true}