# Production Profile - PostgreSQL Database
spring:
  # JPA Configuration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none # Nunca altere o schema em produção
    defer-datasource-initialization: false
    show-sql: false # Desabilitado em produção
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 25
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        cache:
          use_second_level_cache: false
          use_query_cache: false

  # SQL Initialization
  sql:
    init:
      mode: never # Desabilitado em produção

  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:productcatalog}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 30000
      leak-detection-threshold: 60000
      max-lifetime: 1800000
      validation-timeout: 5000
      connection-test-query: SELECT 1

  # Security Headers
  security:
    headers:
      frame-options: DENY
      content-type-options: nosniff
      xss-protection: "1; mode=block"
      referrer-policy: strict-origin-when-cross-origin

# JWT Configuration
jwt:
  public:
    key: "classpath:app.pub"
  private:
    key: "classpath:app.key"
  secret: ${JWT_SECRET:}

# Logging
logging:
  level:
    root: WARN
    org.springframework.security: WARN
    com.victorxavier: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
    max-size: 100MB
    max-history: 30

# Server Configuration
server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

# Management and Actuator for Production
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: never
      show-components: never
  metrics:
    export:
      prometheus:
        enabled: true