# Spring Boot Application Configuration - Mock Profile
spring:
  # Active Profile Configuration
  profiles:
    active: default # Perfil padrão para mock/testes

  # JPA Configuration for Mock
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop # Cria e apaga o schema a cada execução
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  # SQL Initialization
  sql:
    init:
      mode: always

  # H2 In-Memory Database Configuration (Mock)
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;TIME ZONE=UTC
    username: sa
    password: "" # Senha vazia
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

# JWT Configuration (comum para todos os perfis)
jwt:
  public:
    key: "classpath:app.pub"
  private:
    key: "classpath:app.key"

# Management and Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Logging for Mock
logging:
  level:
    org.springframework.security: DEBUG
    com.victorxavier: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Server Configuration
server:
  port: 8080